title: My Essay & Diary
baseurl: "/essay"
permalink: /essay/posts/:year-:month-:day-:title.html
markdown: kramdown
timezone: Asia/Tokyo
paginate: 1
paginate_path: "/essay/page:num/"
gems:
  - jekyll-paginate
